name: kidlearningflutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.14
  video_player: ^2.4.7
  fluttertoast: ^8.0.9
  firebase_core: ^1.14.1
  eva_icons_flutter: ^3.1.0
  avatar_glow: ^2.0.2
  font_awesome_flutter: ^10.2.1
  flutter_speed_dial: ^6.2.0
  audioplayers: ^0.20.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - test_splash.png
    - loginillus.png
    - welsome.png
    - let's.png
    - Alphabet.png
    - sentence.png
    - letterA.png
    - letterA.mp3
    - letterB.png
    - apple.png
    - letterB.mp3
    - ball.png
    - letterC.png
    - letterC.mp3
    - car.png
    - letterD.png
    - letterD.mp3
    - donkey.png
    - letterE.png
    - letterE.mp3
    - egg.png
    - letterF.png
    - letterF.mp3
    - ferry.png
    - letterG.png
    - letterG.mp3
    - grass.png
    - letterH.png
    - letterH.mp3
    - hug.png
    - letterI.png
    - letterI.mp3
    - igloo.png
    - letterJ.png
    - letterJ.mp3
    - jaguar.png
    - letterK.png
    - letterK.mp3
    - kite.png
    - letterL.png
    - letterL.mp3
    - lion.png
    - letterM.png
    - letterM.mp3
    - monkey.png
    - letterN.png
    - letterN.mp3
    - nose.png
    - letterO.png
    - letterO.mp3
    - orange.png
    - letterP.png
    - letterP.mp3
    - panda.png
    - letterQ.png
    - letterQ.mp3
    - queen.png
    - letterR.png
    - letterR.mp3
    - rabbit.png
    - letterS.png
    - letterS.mp3
    - snake.png
    - letterT.png
    - letterT.mp3
    - tiger.png
    - letterU.png
    - letterU.mp3
    - umbre.png
    - letterV.png
    - letterV.mp3
    - violin.png
    - letterW.png
    - letterW.mp3
    - walrus.png
    - letterX.png
    - letterx.mp3
    - xray.png
    - letterY.png
    - letterY.mp3
    - yogurt.png
    - letterZ.png
    - letterZ.mp3
    - zebra.png
    - sentencelevel.png
    - sentencescore.png
    - submitscore.png
    - alpahabetnew.png
    - sentencenew.png
    - gamenew.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
